export const CREATE_ACCOUNT_CHAIN = 'CREATE_ACCOUNT_CHAIN';
export const CREATE_ASSET_CHAIN = 'CREATE_ASSET_CHAIN';
export const FETCH_CHAIN_ERROR = 'FETCH_CHAIN_ERROR';
export const UPDATE_BLOCK_STATE_REJECTED = 'UPDATE_BLOCK_STATE_REJECTED';
export const UPDATE_BLOCK_STATE_ACCEPTED = 'UPDATE_BLOCK_STATE_ACCEPTED';
export const UPDATE_CHAIN = 'UPDATE_CHAIN';
